
url: https://atmcgrath.github.io

baseurl: /demo-site

title: Axolotl

description: The story of an adorable creature

remote_theme: "mmistakes/minimal-mistakes@4.25.0"
# pages-themes/cayman@v0.2.0

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
